### ISSUE TITLE
system.url-prefix should be configurable via env

### ISSUE THREAD

**Issue by xeor** [getsentry/docker-sentry#113]
I was surprised to not see any issues on this. But is there any reasons not to have `system.url-prefix` configurable using an environment variable?

**Comment by matti** [comment]
yes, currently the web app keeps redirecting to containername:9000 instead of my sentry.mydomain.com

**Comment by matti** [comment]
(system.url-prefix didn't help here)

**Comment by Phibedy** [comment]
Any updates here?

**Comment by mattrobenolt** [comment]
This is really old. `SENTRY_URL_PREFIX` I think.

**Comment by mattrobenolt** [comment]
Never mind, I guess you’re right. We don’t. 

What’s the reason to need this configured this way?

**Comment by Phibedy** [comment]
If you are lazy and use the pre-build docker image you can't set it. Therefore no useful links in emails etc.

**Comment by mattrobenolt** [comment]
Yes you can. At first run, you’re prompted to go through a setup wizard, you set it there. Or you can set it at runtime using `sentry config set system.url-prefix ...`. 

We’re probably going to be paring down our environment variable offerings around things like this in the future, not adding more. Since these are really impractical and hard for us to maintain.

**Comment by mattrobenolt** [comment]
You could also, and highly recommended, supply your own sentry.conf.py file and do whatever you want.

**Comment by Phibedy** [comment]
I will go with the `sentry.conf.py` file, thank you for fast support :+1:

**Comment by BYK** [comment]
Closing this as @mattrobenolt's solution seems satisfactory.
