### ISSUE TITLE
docker secrets support

### ISSUE THREAD

**Issue by msva** [getsentry/docker-sentry#164]
Can you add a support for [docker secrets](https://docs.docker.com/v17.09/engine/swarm/secrets/#simple-example-get-started-with-secrets), please?
It will be much more useful to use it for storing environment variables, that is used in `sentry.conf.py`.

I think, best way will be to edit entrypoint script to:
1) choose a name for an environment variable, that will store a name of secrets file (say, SENTRY_SECRET_NAME)
2) `[[ -f /run/secrets/${SENTRY_SECRET_NAME} ]] && source /run/secrets/${SENTRY_SECRET_NAME}`

// and add corresponding directives (and/or comments) to the default compose file

**Comment by tianon** [comment]
FWIW, quite a few other images allow an optional `_FILE` suffix on environment variables which would be useful to use with solutions like Docker Secrets (which allows for more flexible/generic usage, since for example even with Docker Secrets you can ask Docker to mount the secret somewhere other than `/run/secrets`).

**Comment by BYK** [comment]
@tianon @msva  - Would you like to give this a try in a PR and I'll work with you to get it merged? I'm not too familiar with Docker Secrets so I think someone using it actively would be in a better position to make the necessary changes.

**Comment by BYK** [comment]
We won't be working on this in the near future. If anyone is interested feel free to try this over at https://github.com/getsentry/onpremise
