### ISSUE TITLE
Incorrect default SMTP user/password

### ISSUE THREAD

**Issue by Gun5m0k3** [getsentry/docker-sentry#172]
I am using the .env file to control the SMTP settings of my Sentry instance running on Docker. When I omit the keys SENTRY_EMAIL_USER and SENTRY_EMAIL_PASSWORD the page at /manage/status/mail/ tells me that the SMTP user is 'a' (without quotes). When I set a value the correct value is displayed on the aforementioned page. 

So:
`SENTRY_EMAIL_USER=` => displays 'a' on /manage/status/mail/
`SENTRY_EMAIL_USER=foo` => displays 'foo' on /manage/status/mail/

When omitting the user and password from the .env file the SMTP library tries to connect with authentication resulting in the following error:

> SMTP AUTH extension not supported by server.

All my configuration is done in the .env file:

```
SENTRY_SECRET_KEY=<secret>
SENTRY_SINGLE_ORGANIZATION=0

SENTRY_REDIS_HOST=redis
SENTRY_POSTGRES_HOST=postgres

SENTRY_SERVER_EMAIL=Sentry <sentry@domain.com>
SENTRY_EMAIL_HOST=smtp
SENTRY_EMAIL_PORT=25
SENTRY_EMAIL_USER=
SENTRY_EMAIL_PASSWORD=
```

I am running Sentry 9.1.1.

**Comment by BYK** [comment]
Hi @Gun5m0k3, I couldn't find anything that may set this to `'a'`. Could it be possible that you have this value set in your system environment or somewhere else?

Also, can you try with the latest version of this repo just to make sure this is not an issue with an older version (this is unlikely but I just want to make sure).

**Comment by Gun5m0k3** [comment]
Hi @BYK, thanks for responding. I also went through the Sentry codebase and could not find anything that would set the default value to `'a'`. In my Dockerfile I am using the latest Sentry image:

`FROM sentry:latest`

My checkout is up to date with `https://github.com/getsentry/onpremise.git`. I have made no changes to either the `sentry.conf.py` or `config.yml` files. They are as they are in the `master` branch of the aforementioned repository.

Running a git diff in my Sentry project directory returns the following changes:

```
diff --git a/Dockerfile b/Dockerfile
index e5df0de..2176caf 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1 +1 @@
-FROM sentry:9.1-onbuild
+FROM sentry:latest
```

I'm at a total loss as to why this is happening. I will spin up a whole new Sentry installation to see if the issue arises there as well.

**Comment by BYK** [comment]
@Gun5m0k3 thanks for the helpful response! My only advise is to keep using the `onbuild` image instead of the `latest`. Sorry if my earlier comment mislead you, I just meant the latest version of this repo, not any other image. Still, if you'd like to get the latest onbuild image, simply replace `9.1-onbuild` with `onbuild` 😉 

Waiting to hear about your next try and will keep the issue open until then.

**Comment by Gun5m0k3** [comment]
@BYK, I threw everything away (containers and volumes) and set up a new Sentry environment using the same config, guess what: it works now... :). I still have no idea as to why my username showed `'a'`. Some nasty data/cache issue perhaps?

What is the difference between `onbuild` and `latest` btw?

**Comment by BYK** [comment]
>@BYK, I threw everything away (containers and volumes) and set up a new Sentry environment using the same config, guess what: it works now... :)

Glad to hear! Closing the issue then :)

>I still have no idea as to why my username showed 'a'. Some nasty data/cache issue perhaps?

Possibly. Can even be related to browser caching or something if you have only seen this on the `manage` page.

>What is the difference between onbuild and latest btw?

I'll take you to the docs for this: https://hub.docker.com/_/sentry/#sentryonbuild

I also highly recommend you to use getsentry/onpremise instead of this repo as that's much easier to setup and maintain.
