### ISSUE TITLE
Enhnace Dockerfile to automatically load and "install" plugins

### ISSUE THREAD

**Issue by Apollon77** [getsentry/docker-sentry#210]
Hey,

the docker file isgreat but as soom as you want to use custom plugins (e.g. telegram) you are loast and need to manually edit the docker config and stuff. Especially bad when you use the image from docker hub.

It would be awesome to have environment variables to add/install plugins. So e.g.
* ADD_PLUGINS = 'sentry-telegram,sentryplugin2"

And the docker python file run "pip install <name>" and add them to INSTALLED_APPS if successfull.

**Comment by BYK** [comment]
We encourage building your own image on top of this if you want plugins as installing plugins at runtime is not a great option for various reasons. See https://github.com/getsentry/onpremise/blob/master/sentry/Dockerfile on how we do this for the https://github.com/getsentry/onpremise/ repo.

Also, note that this repo is deprecated (see the note on the readme) so we won't be doing any further work in here. You may still look at https://github.com/getsentry/sentry/blob/master/docker/Dockerfile which is the current docker source and file issues there if you still think this is an idea worth pursuing.

**Comment by Apollon77** [comment]
Also when off topic here ... I tried using the referenced one but was not able to start because of the "auto_commit: true" error (there are issues for it) ... so I ended up in having this one basically working. I was also not able to find a real "mapping" of release tags on the other one to "stable" versions. i'm not sure that I want to have "latest" .. else there are only  "hashed versions". SHould I open an issue in the other repo to add versioning tags or at least proper documentation of it? Or do I oversaw something?

**Comment by BYK** [comment]
> I tried using the referenced one but was not able to start because of the "auto_commit: true" error (there are issues for it) ... so I ended up in having this one basically working.

If you follow the instructions on the onpremise repo you should not have any issues. If you reference those issues, I'll look into them again but I'm quite certain they are using a custom installation which is hard for us to diagnose and support.

>I was also not able to find a real "mapping" of release tags on the other one to "stable" versions. i'm not sure that I want to have "latest" .. else there are only "hashed versions". SHould I open an issue in the other repo to add versioning tags or at least proper documentation of it? Or do I oversaw something?

This is intentional because as of version 10 (somewhat earlier actually), releasing a new version is essentially arbitrarily tagging a commit on the repo and assigning that a version tag to that commit (`10.0.0` for this specific case). There's no extra testing or anything else so we strongly recommend using this. If you want/need image stability, we tag all images with the commit SHAs they are built with and push them to Docker Hub so you can pick the version you want to stick with and upgrade at your own pace. To use a specific image on the onpremise repo, you can use the `SENTRY_IMAGE` environment variable. That said none of this is properly documented as you mentioned so I'll get to that.

Feel free to open a new issue over at the onpremise repo to follow the progress regarding docs.

**Comment by Apollon77** [comment]
Thank you, then I will try upgrade to the mentioned docker image and "latest" and we will see how it goes :-)
issue for docs: https://github.com/getsentry/sentry/issues/16638
