### ISSUE TITLE
Bring back regular releases to Docker Hub

### ISSUE THREAD

**Issue by BYK** [getsentry/docker-sentry#211]
_This is a continuation of the discussion from https://github.com/getsentry/docker-sentry/pull/208#issuecomment-578691818_

@yosifkit @tianon - We want to bring back regular Docker Hub releases that is also suitable for your processes. We'd like to follow the process Elasticsearch uses as detailed and explained here: https://github.com/docker-library/official-images/pull/5039

Any objections to that?

**Comment by yosifkit** [comment]
Thanks for the poke over on official-images. Sorry for the slow reply here and for not getting back to #208. :bowing_man:

Elasticsearch, Logstash, and Kibana were the result of extensive discussion and ongoing collaboration with Elastic Inc. and is very unlikely to be repeated.

We'd love to find a way that Sentry images could continue to be published in the official-images program.

Since every change of every image is reviewed by humans, we cannot reasonably review the hourly cadence I see on tags pushed to `getsentry/sentry`. We do not allow nightly builds and instead recommend weekly at most (see also https://github.com/docker-library/julia/issues/25#issuecomment-434867037 and https://github.com/docker-library/php/issues/991).

----

On a related note, the Sentry official-image Hub page is currently complicated by the Docker Store "publisher image" masking the Docker Hub official-image listing similar to [Aerospike](https://github.com/docker-library/official-images/pull/7594#issuecomment-599829610). I am uncertain how this affects `docker pull`.

**Comment by BYK** [comment]
Hi @yosifkit and no worries about the late turn-over, I figured you folks are busy and wasn't sure you were getting notified about external mentions, hence the issue over the official repo 🙂 

>Since every change of every image is reviewed by humans, we cannot reasonably review the hourly cadence I see on tags pushed to getsentry/sentry. We do not allow nightly builds and instead recommend weekly at most (see also docker-library/julia#25 (comment) and docker-library/php#991).

Yes, I definitely agree and the reason I'm bringing this up is because we are planning to switching to CalVer (while keeping the nightlies, but not for the Docker Library image) with a monthly cadence (except for urgent hot fixes). I think this would be a much more manageable load on your side, right?

>Elasticsearch, Logstash, and Kibana were the result of extensive discussion and ongoing collaboration with Elastic Inc. and is very unlikely to be repeated.

I understand this but keeping a separate image and build process, just for the Docker Library is not feasible for us. Our current Docker setup is likely to evolve with more build targets (build base, runtime base, development etc.).

The closest we can get I think might be us having a base `sentry-runtime` image, and then pulling the latest pip wheel into that image but I'd much rather not depend on pip as packing that wheel is also not guaranteed to survive (as our PyPI demand is pretty low after Docker, so yay? 🎉 ).

I'm also open to making our images be more reproducible/consistent with some input from you. I understand that anything that pulls things from `apt` or likes, even with pinned versions may change in time so I don't really know what else we can do.

>On a related note, the Sentry official-image Hub page is currently complicated by the Docker Store "publisher image" masking the Docker Hub official-image listing similar to Aerospike. I am uncertain how this affects docker pull.

I don't know much about this but I don't think we are interested in a Store functionality (I think that explains the $0 thing on that page). Do you know if this can be disabled? Is it us enabling this somehow?

**Comment by BYK** [comment]
@yosifkit ping :)

**Comment by BYK** [comment]
@yosifkit we've published the first of many monthly CalVer releases: https://github.com/getsentry/sentry/releases/20.6.0

LMK when is a good time to finalize this discussion.

**Comment by BYK** [comment]
Closing this and archiving the repo as we decided to remove the image in favor of the full [onpremise package](https://github.com/getsentry/onpremise)
