### ISSUE TITLE
SENTRY_URL_PREFIX / SENTRY_URL_PREFIX is not configured

### ISSUE THREAD

**Issue by pgaubatz** [getsentry/docker-sentry#26]
Hi,

trying to set up sentry according to the documentation (i.e., https://hub.docker.com/_/sentry/) I ran into the following errors:
```
!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!
!! SENTRY_ADMIN_EMAIL is not configured !!
!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!

!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!
!! SENTRY_URL_PREFIX is not configured !!
!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!
```
These errors can be found in the logs of my sentry docker instance (i.e., `docker logs sentry-sentry`) and when running a `sentry upgrade` instance.

```bash
docker run -e "SENTRY_URL_PREFIX=https://x" -e "SENTRY_ADMIN_EMAIL=x@y" -it --rm --link sentry-postgres:postgres --link sentry-redis:redis sentry sentry upgrade
```

My `sentry-sentry` instance has been created using:
```bash
docker run -e "SENTRY_URL_PREFIX=https://x" -e "ADMIN_EMAIL=x@y" -d --name sentry-sentry -p 9001:9000 --link sentry-redis:redis --link sentry-postgres:postgres sentry
```

Any ideas what I might be doing wrong here or might this even be a bug?

Thanks!

Cheers,
Patrick

**Comment by mattrobenolt** [comment]
Hey @pgaubatz, these are technically just warnings.

We didn't write this original Dockerfile, but we have some updates coming in the near future now that we took over official ownership.

Those settings you're trying to configure need to be in our config file, which is at `/home/user/.sentry/sentry.conf.py` inside the container.

I'd recommend just mounting in your own config, since it's not configurable through environment variables, and likely won't since we have too many settings.

You can find instructions for configuring here: https://docs.getsentry.com/on-premise/server/config/

I hope this helps in the meantime while we work to get this straightened up.

I plan on redoing and officially documenting this for our 8.0 release. :)

**Comment by pgaubatz** [comment]
Hi @mattrobenolt,

thanks for clarifying!

Cheers!
