### ISSUE TITLE
remote redis with password

### ISSUE THREAD

**Issue by SUNNYANDPJ** [getsentry/docker-sentry#62]
I use a local postgresql container with link command.
&
I use remote redis with password.I add 'password' to redis config in sentry.conf.py and I also build a new image.Upgrade and run well.But when I visit from Browser, "Bad Request (400)" display.

**Comment by SUNNYANDPJ** [comment]
@mattrobenolt

**Comment by SUNNYANDPJ** [comment]
May I use a redis-cli container to connect to remote redis.
@macqueen @mattrobenolt

**Comment by mattrobenolt** [comment]
Hey @SUNNYANDPJ, first of all, our issue trackers are not a support channel. Issues are for bug reports, not just general assistance on getting things working. If documentation needs clarified, that's one thing and we'll fix it, but we don't provide general support otherwise. See https://docs.getsentry.com/on-premise/support/ for options on getting support for running your own Sentry instance.

With that said, I'll try and help you out here, but in the future, issues that are general questions and not related to bugs will be closed.

> But when I visit from Browser, "Bad Request (400)" display.

This has nothing to do with Redis, and has nothing to do with Docker, so definitely doesn't belong here. But, there is an open issue to improve the issue around this here: https://github.com/getsentry/sentry/issues/3048 I've just submit a Pull Request to add this into our FAQ since this question comes up often enough: https://github.com/getsentry/sentry/pull/3052

The problem is your `system.url-prefix` setting doesn't match what you're trying to load Sentry as. Please read our documentation.

> May I use a redis-cli container connect to remote redis to replace a redis container?

I don't know what this means nor do I know how it relates to Sentry, so I can't really comment. It sounds like you're asking more of a general "how to use Docker" question, and this isn't the proper place for us to teach this to you.

In the future, please be respectful of our time and don't abuse our issue trackers.

**Comment by SUNNYANDPJ** [comment]
Oh~I am sorry
@mattrobenolt
