### ISSUE TITLE
How to set SENTRY_SMTP_HOSTNAME ?

### ISSUE THREAD

**Issue by LoicMahieu** [getsentry/docker-sentry#63]
Related to #55 , I wish use [inbound email via Mailgun](https://docs.getsentry.com/on-premise/server/inbound-mail/).
I need to specify the `SENTRY_SMTP_HOSTNAME` option in order to replace default value: `localhost`.

I saw in #29 that it would be fixed in 8.0 but I don't see any mention of this in the sentry.conf.py file.

Am I wrong ? Thanks

**Comment by mattrobenolt** [comment]
Ah, crap. So #29 was a bit misleading, at least for me.

There are SMTP configuration details related to output email. This is what was resolved for 8.0.

Looking at this now in Sentry, we should probably kill this setting. We have both `SENTRY_SMTP_HOST` and `SENTRY_SMTP_HOSTNAME`. :(

`SENTRY_SMTP_HOSTNAME` as you pointed out, is related to inbound email. And this does not have support yet in docker-sentry. I'm going to see how hard it is to deprecate this setting, and instead of default to `localhost`, it should be derived from `mail.from` instead. This value gets utilized for the `Reply-To` email header only email `ENABLE_EMAIL_REPLIES` is set.

I can cram this into the 8.3 image in the meantime though, just giving some context to an underutilized feature. :)
