### ISSUE TITLE
Leverage overlay networks rather than linked containers

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/docker-sentry#69]

**Comment by Bastien-** [comment]
I am trying to scale sentry on AWS ECS and found that the linked containers need to be on the same host. This limits greatly the scaling strategy since it does not take advantage of the multi-host cluster. It can only scale up by switching to a bigger host containing the linked containers.  
I believe an overlay network would help to spread the containers on various hosts. Is this issue related to that matter? And if yes, then would you care to describe roughly what is needed to get there? So I can evaluate if I can contribute.

**Comment by mattrobenolt** [comment]
This isn't really related. This ticket is for just a better example in the docker-compose file. But setting stuff up to be multi machine would be done the same as any other system. You edit config files and provide IP and ports.

**Comment by BYK** [comment]
@mattrobenolt - Is this still relevant? If so, I feel like this should be moved over to getsentry/onpremise. What do you think?

**Comment by mattrobenolt** [comment]
Honestly, I know very little about this or what we'd need to do to support it. I've never used this. I know linked containers aren't ideal, since they're extremely limiting, but it's a good simple way to get things started. I'm not sure how you'd do it otherwise.

**Comment by BYK** [comment]
I've read all the docs around this and seems like we don't need to do anything extra:

 - We already don't use links
 - Docker already uses an overlay network in swarm mode

We should be good to go so closing this out until someone actually complains.
